# Generated by Django 4.2.2 on 2023-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_comment_is_anonymous_comment_is_secret_refly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200, null=True)),
                (
                    "category_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("selected", models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
