# Generated by Django 4.2.2 on 2023-06-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="foreign_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.category",
            ),
        ),
    ]
